id: IFE4C2204
legacy_id: P010378
ocr_import_info:
  bdrc_scan_id: W29911
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:22:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:43:24.612267+00:00'
last_modified: 2022-09-02 22:44:56.583738
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29911
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29911
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཁོན་ལུགས་ཕུར་པའི་ཆོས་སྐོར།
  author: ས་སྐྱ་ཁྲི་ཆེན ༢༣་ཀུན་དགའ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.7814303997683473
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I5699:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5699
      total_pages: 990
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5699.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7814303997683473
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
