id: IFE4C2204
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:27:56+00:00'
last_modified: '2022-06-08T13:09:41.162860+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29911
  title: འཁོན་ལུགས་ཕུར་པའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0CF4:
      image_group_id: I5699
      title: ''
      total_pages: 990
      order: 1
      base_file: 0CF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
