id: P010378
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W29911
  title: འཁོན་ལུགས་ཕུར་པའི་ཆོས་སྐོར།
  author: ''
  volumes:
    7ca9623d14d44894950e10ad1e2fe211:
      image_group_id: I5699
      title: ''
      volume_number: 1
      total_pages: 990
      base_file: v001.txt
